# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KodiRemote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KodiRemote
	pod 'UPnAtom', :git => 'https://github.com/master-nevi/UPnAtom.git'
  
  	pod 'Kingfisher', '~> 3.0'
  
	# pod "MobilePlayer"
end
